import 'package:anvil_foundry/anvil_foundry.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

/// Extra categorized icons for goal/tracker/project/event entity pickers.
const IconSet companionEntityPickerIcons = IconSet(
  categories: [
    IconCategory(name: 'Health & fitness', sequence: 10),
    IconCategory(name: 'Mind & learning', sequence: 11),
    IconCategory(name: 'Work & money', sequence: 12),
    IconCategory(name: 'Home & life', sequence: 13),
    IconCategory(name: 'Creative & media', sequence: 14),
    IconCategory(name: 'Nature & travel', sequence: 15),
    IconCategory(name: 'Sports & games', sequence: 16),
    IconCategory(name: 'Communication', sequence: 17),
  ],
  entries: [
    // Health & fitness
    IconEntry(
      name: 'Dumbbell',
      data: FontAwesomeIcons.dumbbell,
      category: 'Health & fitness',
      sequence: 0,
      tags: ['health', 'fitness', 'gym', 'workout', 'strength', 'exercise'],
    ),
    IconEntry(
      name: 'Heart',
      data: FontAwesomeIcons.heart,
      category: 'Health & fitness',
      sequence: 1,
      tags: ['health', 'heart', 'love', 'wellness', 'cardio'],
    ),
    IconEntry(
      name: 'Person Running',
      data: FontAwesomeIcons.personRunning,
      category: 'Health & fitness',
      sequence: 2,
      tags: ['health', 'running', 'cardio', 'jog', 'exercise'],
    ),
    IconEntry(
      name: 'Bed',
      data: FontAwesomeIcons.bed,
      category: 'Health & fitness',
      sequence: 3,
      tags: ['health', 'sleep', 'rest', 'bed', 'recovery'],
    ),
    IconEntry(
      name: 'Apple Whole',
      data: FontAwesomeIcons.appleWhole,
      category: 'Health & fitness',
      sequence: 4,
      tags: ['health', 'nutrition', 'food', 'apple', 'diet'],
    ),
    IconEntry(
      name: 'Droplet',
      data: FontAwesomeIcons.droplet,
      category: 'Health & fitness',
      sequence: 5,
      tags: ['health', 'water', 'hydration', 'drink'],
    ),
    IconEntry(
      name: 'Weight Scale',
      data: FontAwesomeIcons.weightScale,
      category: 'Health & fitness',
      sequence: 6,
      tags: ['health', 'weight', 'scale', 'fitness', 'body'],
    ),
    IconEntry(
      name: 'Stethoscope',
      data: FontAwesomeIcons.stethoscope,
      category: 'Health & fitness',
      sequence: 7,
      tags: ['health', 'medical', 'doctor', 'checkup'],
    ),
    IconEntry(
      name: 'Spa',
      data: FontAwesomeIcons.spa,
      category: 'Health & fitness',
      sequence: 8,
      tags: ['health', 'spa', 'relax', 'wellness', 'self-care'],
    ),
    IconEntry(
      name: 'Person Biking',
      data: FontAwesomeIcons.personBiking,
      category: 'Health & fitness',
      sequence: 9,
      tags: ['health', 'cycling', 'bike', 'cardio', 'exercise'],
    ),

    // Mind & learning
    IconEntry(
      name: 'Book',
      data: FontAwesomeIcons.book,
      category: 'Mind & learning',
      sequence: 0,
      tags: ['mind', 'learning', 'book', 'read', 'study'],
    ),
    IconEntry(
      name: 'Brain',
      data: FontAwesomeIcons.brain,
      category: 'Mind & learning',
      sequence: 1,
      tags: ['mind', 'brain', 'thinking', 'mental', 'focus'],
    ),
    IconEntry(
      name: 'Graduation Cap',
      data: FontAwesomeIcons.graduationCap,
      category: 'Mind & learning',
      sequence: 2,
      tags: ['mind', 'learning', 'education', 'school', 'degree'],
    ),
    IconEntry(
      name: 'Lightbulb',
      data: FontAwesomeIcons.lightbulb,
      category: 'Mind & learning',
      sequence: 3,
      tags: ['mind', 'idea', 'insight', 'creativity', 'learning'],
    ),
    IconEntry(
      name: 'Pen',
      data: FontAwesomeIcons.pen,
      category: 'Mind & learning',
      sequence: 4,
      tags: ['mind', 'write', 'journal', 'notes', 'learning'],
    ),
    IconEntry(
      name: 'Language',
      data: FontAwesomeIcons.language,
      category: 'Mind & learning',
      sequence: 5,
      tags: ['mind', 'language', 'translate', 'learning', 'study'],
    ),
    IconEntry(
      name: 'Book Open',
      data: FontAwesomeIcons.bookOpen,
      category: 'Mind & learning',
      sequence: 6,
      tags: ['mind', 'reading', 'book', 'study', 'learning'],
    ),
    IconEntry(
      name: 'Glasses',
      data: FontAwesomeIcons.glasses,
      category: 'Mind & learning',
      sequence: 7,
      tags: ['mind', 'reading', 'study', 'focus', 'learning'],
    ),
    IconEntry(
      name: 'Puzzle Piece',
      data: FontAwesomeIcons.puzzlePiece,
      category: 'Mind & learning',
      sequence: 8,
      tags: ['mind', 'puzzle', 'problem', 'thinking', 'logic'],
    ),
    IconEntry(
      name: 'Scroll',
      data: FontAwesomeIcons.scroll,
      category: 'Mind & learning',
      sequence: 9,
      tags: ['mind', 'learning', 'history', 'study', 'notes'],
    ),

    // Work & money
    IconEntry(
      name: 'Briefcase',
      data: FontAwesomeIcons.briefcase,
      category: 'Work & money',
      sequence: 0,
      tags: ['work', 'job', 'career', 'business', 'office'],
    ),
    IconEntry(
      name: 'Laptop',
      data: FontAwesomeIcons.laptop,
      category: 'Work & money',
      sequence: 1,
      tags: ['work', 'computer', 'laptop', 'remote', 'office'],
    ),
    IconEntry(
      name: 'Building',
      data: FontAwesomeIcons.building,
      category: 'Work & money',
      sequence: 2,
      tags: ['work', 'office', 'building', 'company', 'business'],
    ),
    IconEntry(
      name: 'Wallet',
      data: FontAwesomeIcons.wallet,
      category: 'Work & money',
      sequence: 3,
      tags: ['money', 'wallet', 'finance', 'budget', 'spending'],
    ),
    IconEntry(
      name: 'Coins',
      data: FontAwesomeIcons.coins,
      category: 'Work & money',
      sequence: 4,
      tags: ['money', 'coins', 'finance', 'savings', 'budget'],
    ),
    IconEntry(
      name: 'Pie Chart',
      data: FontAwesomeIcons.chartPie,
      category: 'Work & money',
      sequence: 5,
      tags: ['work', 'chart', 'analytics', 'finance', 'stats'],
    ),
    IconEntry(
      name: 'Clipboard',
      data: FontAwesomeIcons.clipboard,
      category: 'Work & money',
      sequence: 6,
      tags: ['work', 'clipboard', 'tasks', 'planning', 'office'],
    ),
    IconEntry(
      name: 'Desktop',
      data: FontAwesomeIcons.desktop,
      category: 'Work & money',
      sequence: 7,
      tags: ['work', 'computer', 'desktop', 'office', 'tech'],
    ),
    IconEntry(
      name: 'File Lines',
      data: FontAwesomeIcons.fileLines,
      category: 'Work & money',
      sequence: 8,
      tags: ['work', 'document', 'file', 'report', 'notes'],
    ),
    IconEntry(
      name: 'Sack Dollar',
      data: FontAwesomeIcons.sackDollar,
      category: 'Work & money',
      sequence: 9,
      tags: ['money', 'finance', 'savings', 'wealth', 'budget'],
    ),

    // Home & life
    IconEntry(
      name: 'Utensils',
      data: FontAwesomeIcons.utensils,
      category: 'Home & life',
      sequence: 0,
      tags: ['home', 'food', 'cooking', 'meal', 'kitchen'],
    ),
    IconEntry(
      name: 'Mug Hot',
      data: FontAwesomeIcons.mugHot,
      category: 'Home & life',
      sequence: 1,
      tags: ['home', 'coffee', 'tea', 'drink', 'morning'],
    ),
    IconEntry(
      name: 'Shirt',
      data: FontAwesomeIcons.shirt,
      category: 'Home & life',
      sequence: 2,
      tags: ['home', 'clothes', 'laundry', 'wardrobe', 'life'],
    ),
    IconEntry(
      name: 'Paw',
      data: FontAwesomeIcons.paw,
      category: 'Home & life',
      sequence: 3,
      tags: ['home', 'pet', 'dog', 'cat', 'animal'],
    ),
    IconEntry(
      name: 'Baby',
      data: FontAwesomeIcons.baby,
      category: 'Home & life',
      sequence: 4,
      tags: ['home', 'family', 'baby', 'parenting', 'life'],
    ),
    IconEntry(
      name: 'Key',
      data: FontAwesomeIcons.key,
      category: 'Home & life',
      sequence: 5,
      tags: ['home', 'key', 'security', 'house', 'access'],
    ),
    IconEntry(
      name: 'Couch',
      data: FontAwesomeIcons.couch,
      category: 'Home & life',
      sequence: 6,
      tags: ['home', 'furniture', 'relax', 'living', 'comfort'],
    ),
    IconEntry(
      name: 'Broom',
      data: FontAwesomeIcons.broom,
      category: 'Home & life',
      sequence: 7,
      tags: ['home', 'cleaning', 'chores', 'house', 'tidy'],
    ),
    IconEntry(
      name: 'Dog',
      data: FontAwesomeIcons.dog,
      category: 'Home & life',
      sequence: 8,
      tags: ['home', 'pet', 'dog', 'animal', 'walk'],
    ),
    IconEntry(
      name: 'Gift',
      data: FontAwesomeIcons.gift,
      category: 'Home & life',
      sequence: 9,
      tags: ['home', 'gift', 'celebration', 'birthday', 'life'],
    ),

    // Creative & media
    IconEntry(
      name: 'Palette',
      data: FontAwesomeIcons.palette,
      category: 'Creative & media',
      sequence: 0,
      tags: ['creative', 'art', 'design', 'color', 'paint'],
    ),
    IconEntry(
      name: 'Music',
      data: FontAwesomeIcons.music,
      category: 'Creative & media',
      sequence: 1,
      tags: ['creative', 'music', 'audio', 'song', 'practice'],
    ),
    IconEntry(
      name: 'Camera',
      data: FontAwesomeIcons.camera,
      category: 'Creative & media',
      sequence: 2,
      tags: ['creative', 'photo', 'camera', 'media', 'capture'],
    ),
    IconEntry(
      name: 'Microphone',
      data: FontAwesomeIcons.microphone,
      category: 'Creative & media',
      sequence: 3,
      tags: ['creative', 'audio', 'podcast', 'voice', 'record'],
    ),
    IconEntry(
      name: 'Paintbrush',
      data: FontAwesomeIcons.paintbrush,
      category: 'Creative & media',
      sequence: 4,
      tags: ['creative', 'art', 'paint', 'design', 'draw'],
    ),
    IconEntry(
      name: 'Gamepad',
      data: FontAwesomeIcons.gamepad,
      category: 'Creative & media',
      sequence: 5,
      tags: ['creative', 'gaming', 'play', 'hobby', 'fun'],
    ),
    IconEntry(
      name: 'Headphones',
      data: FontAwesomeIcons.headphones,
      category: 'Creative & media',
      sequence: 6,
      tags: ['creative', 'music', 'audio', 'listen', 'media'],
    ),
    IconEntry(
      name: 'Podcast',
      data: FontAwesomeIcons.podcast,
      category: 'Creative & media',
      sequence: 7,
      tags: ['creative', 'podcast', 'audio', 'media', 'listen'],
    ),
    IconEntry(
      name: 'Video',
      data: FontAwesomeIcons.video,
      category: 'Creative & media',
      sequence: 8,
      tags: ['creative', 'video', 'film', 'media', 'record'],
    ),
    IconEntry(
      name: 'Masks Theater',
      data: FontAwesomeIcons.masksTheater,
      category: 'Creative & media',
      sequence: 9,
      tags: ['creative', 'theater', 'drama', 'performance', 'art'],
    ),

    // Nature & travel
    IconEntry(
      name: 'Tree',
      data: FontAwesomeIcons.tree,
      category: 'Nature & travel',
      sequence: 0,
      tags: ['nature', 'tree', 'outdoors', 'environment', 'park'],
    ),
    IconEntry(
      name: 'Leaf',
      data: FontAwesomeIcons.leaf,
      category: 'Nature & travel',
      sequence: 1,
      tags: ['nature', 'leaf', 'eco', 'green', 'outdoors'],
    ),
    IconEntry(
      name: 'Sun',
      data: FontAwesomeIcons.sun,
      category: 'Nature & travel',
      sequence: 2,
      tags: ['nature', 'sun', 'weather', 'day', 'outdoors'],
    ),
    IconEntry(
      name: 'Cloud',
      data: FontAwesomeIcons.cloud,
      category: 'Nature & travel',
      sequence: 3,
      tags: ['nature', 'cloud', 'weather', 'sky', 'outdoors'],
    ),
    IconEntry(
      name: 'Plane',
      data: FontAwesomeIcons.plane,
      category: 'Nature & travel',
      sequence: 4,
      tags: ['travel', 'flight', 'plane', 'trip', 'vacation'],
    ),
    IconEntry(
      name: 'Car',
      data: FontAwesomeIcons.car,
      category: 'Nature & travel',
      sequence: 5,
      tags: ['travel', 'car', 'drive', 'commute', 'trip'],
    ),
    IconEntry(
      name: 'Map',
      data: FontAwesomeIcons.map,
      category: 'Nature & travel',
      sequence: 6,
      tags: ['travel', 'map', 'navigation', 'trip', 'explore'],
    ),
    IconEntry(
      name: 'Mountain',
      data: FontAwesomeIcons.mountain,
      category: 'Nature & travel',
      sequence: 7,
      tags: ['nature', 'mountain', 'hike', 'outdoors', 'travel'],
    ),
    IconEntry(
      name: 'Compass',
      data: FontAwesomeIcons.compass,
      category: 'Nature & travel',
      sequence: 8,
      tags: ['travel', 'compass', 'navigation', 'explore', 'adventure'],
    ),
    IconEntry(
      name: 'Ship',
      data: FontAwesomeIcons.ship,
      category: 'Nature & travel',
      sequence: 9,
      tags: ['travel', 'ship', 'cruise', 'vacation', 'sea'],
    ),

    // Sports & games
    IconEntry(
      name: 'Trophy',
      data: FontAwesomeIcons.trophy,
      category: 'Sports & games',
      sequence: 0,
      tags: ['sports', 'trophy', 'win', 'achievement', 'goal'],
    ),
    IconEntry(
      name: 'Medal',
      data: FontAwesomeIcons.medal,
      category: 'Sports & games',
      sequence: 1,
      tags: ['sports', 'medal', 'award', 'achievement', 'win'],
    ),
    IconEntry(
      name: 'Football',
      data: FontAwesomeIcons.football,
      category: 'Sports & games',
      sequence: 2,
      tags: ['sports', 'football', 'soccer', 'game', 'team'],
    ),
    IconEntry(
      name: 'Basketball',
      data: FontAwesomeIcons.basketball,
      category: 'Sports & games',
      sequence: 3,
      tags: ['sports', 'basketball', 'game', 'team', 'exercise'],
    ),
    IconEntry(
      name: 'Bicycle',
      data: FontAwesomeIcons.bicycle,
      category: 'Sports & games',
      sequence: 4,
      tags: ['sports', 'cycling', 'bike', 'exercise', 'outdoors'],
    ),
    IconEntry(
      name: 'Chess',
      data: FontAwesomeIcons.chess,
      category: 'Sports & games',
      sequence: 5,
      tags: ['games', 'chess', 'strategy', 'board', 'hobby'],
    ),
    IconEntry(
      name: 'Person Swimming',
      data: FontAwesomeIcons.personSwimming,
      category: 'Sports & games',
      sequence: 6,
      tags: ['sports', 'swimming', 'pool', 'exercise', 'fitness'],
    ),
    IconEntry(
      name: 'Volleyball',
      data: FontAwesomeIcons.volleyball,
      category: 'Sports & games',
      sequence: 7,
      tags: ['sports', 'volleyball', 'game', 'team', 'beach'],
    ),
    IconEntry(
      name: 'Golf Ball',
      data: FontAwesomeIcons.golfBallTee,
      category: 'Sports & games',
      sequence: 8,
      tags: ['sports', 'golf', 'game', 'outdoors', 'hobby'],
    ),
    IconEntry(
      name: 'Dice',
      data: FontAwesomeIcons.dice,
      category: 'Sports & games',
      sequence: 9,
      tags: ['games', 'dice', 'board', 'fun', 'hobby'],
    ),

    // Communication
    IconEntry(
      name: 'Envelope',
      data: FontAwesomeIcons.envelope,
      category: 'Communication',
      sequence: 0,
      tags: ['communication', 'email', 'mail', 'message', 'inbox'],
    ),
    IconEntry(
      name: 'Phone',
      data: FontAwesomeIcons.phone,
      category: 'Communication',
      sequence: 1,
      tags: ['communication', 'phone', 'call', 'contact', 'talk'],
    ),
    IconEntry(
      name: 'Comment',
      data: FontAwesomeIcons.comment,
      category: 'Communication',
      sequence: 2,
      tags: ['communication', 'comment', 'chat', 'message', 'talk'],
    ),
    IconEntry(
      name: 'Bell',
      data: FontAwesomeIcons.bell,
      category: 'Communication',
      sequence: 3,
      tags: ['communication', 'notification', 'reminder', 'alert', 'bell'],
    ),
    IconEntry(
      name: 'Users',
      data: FontAwesomeIcons.users,
      category: 'Communication',
      sequence: 4,
      tags: ['communication', 'people', 'team', 'group', 'social'],
    ),
    IconEntry(
      name: 'Handshake',
      data: FontAwesomeIcons.handshake,
      category: 'Communication',
      sequence: 5,
      tags: ['communication', 'meeting', 'network', 'deal', 'social'],
    ),
    IconEntry(
      name: 'Comments',
      data: FontAwesomeIcons.comments,
      category: 'Communication',
      sequence: 6,
      tags: ['communication', 'chat', 'discussion', 'message', 'social'],
    ),
    IconEntry(
      name: 'Share Nodes',
      data: FontAwesomeIcons.shareNodes,
      category: 'Communication',
      sequence: 7,
      tags: ['communication', 'share', 'social', 'network', 'connect'],
    ),
    IconEntry(
      name: 'Paper Plane',
      data: FontAwesomeIcons.paperPlane,
      category: 'Communication',
      sequence: 8,
      tags: ['communication', 'send', 'message', 'mail', 'chat'],
    ),
    IconEntry(
      name: 'User Group',
      data: FontAwesomeIcons.userGroup,
      category: 'Communication',
      sequence: 9,
      tags: ['communication', 'community', 'team', 'group', 'people'],
    ),
  ],
);
